package store

// Store-layer helpers needed by the admin "Mark key compromised"
// action. Two reads layered on top of the existing schema:
//
//   - GetAPIKeyByID: fetch a single api_key row by its key_id so the
//     admin handler can verify scope (admin vs read/write) before
//     suspending the project.
//
//   - ListExecutionsByAPIKey: pull every execution authored by a
//     specific api_key_id (column added in migration 035) within a
//     time window. Backs the "what did this key do" report we hand
//     back to the customer.

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"mesedi/backend/internal/events"
)

// --- SQLite impls --------------------------------------------------

// GetAPIKeyByID returns one APIKey by its key_id. key_hash is
// intentionally not selected; the admin handler does not need it.
func (s *SQLiteStore) GetAPIKeyByID(ctx context.Context, keyID string) (*APIKey, error) {
	if keyID == "" {
		return nil, errors.New("GetAPIKeyByID: empty key id")
	}
	row := s.db.QueryRowContext(ctx, `
		SELECT key_id, project_id, key_prefix, name, created_at,
		       last_used_at, scope, expires_at, source
		FROM api_keys
		WHERE key_id = ?
	`, keyID)
	k, err := scanOneAPIKeyRow(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get api_key by id: %w", err)
	}
	return k, nil
}

// ListExecutionsByAPIKey returns executions authored by keyID within
// [t1, t2]. Zero t2 means "now". Limit caps the result; pass 0 for
// the default of 1000 (matches the per-key forensic-report cap).
// Backs the recent-use report generated by the admin "Mark key
// compromised" action.
func (s *SQLiteStore) ListExecutionsByAPIKey(
	ctx context.Context, keyID string, t1, t2 time.Time, limit int,
) ([]*events.Execution, error) {
	if keyID == "" {
		return nil, errors.New("ListExecutionsByAPIKey: empty key id")
	}
	if limit <= 0 {
		limit = 1000
	}
	args := []any{keyID}
	clauses := []string{"api_key_id = ?"}
	if !t1.IsZero() {
		clauses = append(clauses, "started_at >= ?")
		args = append(args, t1.UTC())
	}
	if !t2.IsZero() {
		clauses = append(clauses, "started_at <= ?")
		args = append(args, t2.UTC())
	}
	args = append(args, limit)
	rows, err := s.db.QueryContext(ctx, `
		SELECT execution_id, project_id, parent_execution_id, status,
		       started_at, ended_at, duration_ms,
		       total_tokens_in, total_tokens_out, estimated_cost_usd,
		       input_summary, output_summary, crash_signature,
		       sdk_version, sdk_language
		FROM executions
		WHERE `+joinSQLClauses(clauses)+`
		ORDER BY started_at DESC
		LIMIT ?
	`, args...)
	if err != nil {
		return nil, fmt.Errorf("list executions by api_key: %w", err)
	}
	defer rows.Close()
	return scanForensicExecutionRows(rows)
}

// --- Postgres impls ------------------------------------------------

// GetAPIKeyByID is the Postgres twin of the SQLite method.
func (s *PostgresStore) GetAPIKeyByID(ctx context.Context, keyID string) (*APIKey, error) {
	if keyID == "" {
		return nil, errors.New("GetAPIKeyByID: empty key id")
	}
	row := s.db.QueryRowContext(ctx, `
		SELECT key_id, project_id, key_prefix, name, created_at,
		       last_used_at, scope, expires_at, source
		FROM api_keys
		WHERE key_id = $1
	`, keyID)
	k, err := scanOneAPIKeyRow(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get api_key by id (postgres): %w", err)
	}
	return k, nil
}

// ListExecutionsByAPIKey is the Postgres twin of the SQLite method.
func (s *PostgresStore) ListExecutionsByAPIKey(
	ctx context.Context, keyID string, t1, t2 time.Time, limit int,
) ([]*events.Execution, error) {
	if keyID == "" {
		return nil, errors.New("ListExecutionsByAPIKey: empty key id")
	}
	if limit <= 0 {
		limit = 1000
	}
	args := []any{keyID}
	clauses := []string{"api_key_id = $1"}
	if !t1.IsZero() {
		clauses = append(clauses,
			fmt.Sprintf("started_at >= $%d", len(args)+1))
		args = append(args, t1.UTC())
	}
	if !t2.IsZero() {
		clauses = append(clauses,
			fmt.Sprintf("started_at <= $%d", len(args)+1))
		args = append(args, t2.UTC())
	}
	args = append(args, limit)
	limitPlaceholder := fmt.Sprintf("$%d", len(args))
	rows, err := s.db.QueryContext(ctx, `
		SELECT execution_id, project_id, parent_execution_id, status,
		       started_at, ended_at, duration_ms,
		       total_tokens_in, total_tokens_out, estimated_cost_usd,
		       input_summary, output_summary, crash_signature,
		       sdk_version, sdk_language
		FROM executions
		WHERE `+joinSQLClauses(clauses)+`
		ORDER BY started_at DESC
		LIMIT `+limitPlaceholder, args...)
	if err != nil {
		return nil, fmt.Errorf("list executions by api_key (postgres): %w", err)
	}
	defer rows.Close()
	return scanForensicExecutionRows(rows)
}

// --- shared scanners ----------------------------------------------

// scanOneAPIKeyRow consumes a single *sql.Row produced by the SELECT
// in GetAPIKeyByID. Column order MUST match. Returns sql.ErrNoRows
// when the row is absent; the caller maps that to ErrNotFound.
func scanOneAPIKeyRow(row *sql.Row) (*APIKey, error) {
	var (
		k          APIKey
		createdAt  string
		lastUsedAt sql.NullString
		name       sql.NullString
	)
	if err := row.Scan(
		&k.KeyID, &k.ProjectID, &k.KeyPrefix,
		&name, &createdAt, &lastUsedAt, &k.Scope, &k.ExpiresAt, &k.Source,
	); err != nil {
		return nil, err
	}
	if name.Valid {
		k.Name = name.String
	}
	k.CreatedAt = parseFlexTime(createdAt)
	if lastUsedAt.Valid {
		t := parseFlexTime(lastUsedAt.String)
		if !t.IsZero() {
			k.LastUsedAt = &t
		}
	}
	return &k, nil
}

// scanForensicExecutionRows materializes the rows returned by
// ListExecutionsByAPIKey. The column list is a subset of the
// canonical Execution columns (no tenant_id, paused state, or
// failure_group_id); those fields are not needed by the recent-use
// report and skipping them keeps the scanner simple.
func scanForensicExecutionRows(rows *sql.Rows) ([]*events.Execution, error) {
	out := make([]*events.Execution, 0, 16)
	for rows.Next() {
		e := &events.Execution{}
		var (
			parentID, inputSummary, outputSummary sql.NullString
			crashSig, sdkVersion, sdkLanguage     sql.NullString
			endedAt                               sql.NullTime
			durationMs                            sql.NullInt64
			tokensIn, tokensOut                   sql.NullInt64
			costUSD                               sql.NullFloat64
		)
		if err := rows.Scan(
			&e.ExecutionID, &e.ProjectID, &parentID, &e.Status,
			&e.StartedAt, &endedAt, &durationMs,
			&tokensIn, &tokensOut, &costUSD,
			&inputSummary, &outputSummary, &crashSig,
			&sdkVersion, &sdkLanguage,
		); err != nil {
			return nil, fmt.Errorf("scan forensic execution: %w", err)
		}
		if parentID.Valid {
			s := parentID.String
			e.ParentExecutionID = &s
		}
		if endedAt.Valid {
			t := endedAt.Time.UTC()
			e.EndedAt = &t
		}
		if durationMs.Valid {
			e.DurationMs = durationMs.Int64
		}
		if tokensIn.Valid {
			e.TotalTokensIn = int(tokensIn.Int64)
		}
		if tokensOut.Valid {
			e.TotalTokensOut = int(tokensOut.Int64)
		}
		if costUSD.Valid {
			e.EstimatedCostUSD = costUSD.Float64
		}
		if inputSummary.Valid {
			e.InputSummary = inputSummary.String
		}
		if outputSummary.Valid {
			e.OutputSummary = outputSummary.String
		}
		if crashSig.Valid {
			e.CrashSignature = crashSig.String
		}
		if sdkVersion.Valid {
			e.SDKVersion = sdkVersion.String
		}
		if sdkLanguage.Valid {
			e.SDKLanguage = sdkLanguage.String
		}
		out = append(out, e)
	}
	return out, rows.Err()
}
