package store

// Per-project detector-allowlist storage (Wave Allowlist.a).
// SQLite implementation (migration 049). Matches the
// postgres_project_detector_allowlist.go twin field-for-field.
//
// Schema lives in migrations/049_project_detector_allowlist.sql.
// One row per allowlist entry, indexed by (project_id, detector)
// for the per-failure-class hot-path read.
//
// The caller (API handler) is responsible for:
//   - Validating detector ∈ allow-list ('crashes', 'tool_failures',
//     'validator_failures'). The store accepts any string; keeping
//     the allow-list at the API edge means a future fourth
//     allowlist-supporting detector drops in with no store change.
//   - Validating allowlist_key length (cap 200) and absence of
//     control characters.
//   - Enforcing PROJECT_ALLOWLIST_MAX per (project_id, detector).

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// AllowlistEntry is one row of the project_detector_allowlist table.
type AllowlistEntry struct {
	AllowlistID  string `json:"allowlist_id"`
	ProjectID    string `json:"-"`
	Detector     string `json:"detector"`
	AllowlistKey string `json:"allowlist_key"`
	Reason       string `json:"reason"`
	CreatedBy    string `json:"created_by"`
	CreatedAt    string `json:"created_at"`
	MatchCount   int    `json:"match_count"`
}

// ListProjectAllowlist returns the customer-defined allowlist
// entries for the given (projectID, detector) pair, ordered by
// created_at ascending (oldest first — preserves customer-perceived
// row stability across dashboard reloads).
func (s *SQLiteStore) ListProjectAllowlist(
	ctx context.Context,
	projectID, detector string,
) ([]*AllowlistEntry, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT allowlist_id, project_id, detector, allowlist_key,
		       reason, created_by, created_at, match_count
		FROM project_detector_allowlist
		WHERE project_id = ? AND detector = ?
		ORDER BY created_at ASC
	`, projectID, detector)
	if err != nil {
		return nil, fmt.Errorf("list project_detector_allowlist: %w", err)
	}
	defer rows.Close()

	var out []*AllowlistEntry
	for rows.Next() {
		e := &AllowlistEntry{}
		if err := rows.Scan(
			&e.AllowlistID, &e.ProjectID, &e.Detector, &e.AllowlistKey,
			&e.Reason, &e.CreatedBy, &e.CreatedAt, &e.MatchCount,
		); err != nil {
			return nil, fmt.Errorf("scan project_detector_allowlist row: %w", err)
		}
		out = append(out, e)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows.Err on project_detector_allowlist scan: %w", err)
	}
	return out, nil
}

// GetProjectAllowlistEntry fetches a single entry by primary key.
// Returns ErrNotFound when (projectID, allowlistID) doesn't exist
// or belongs to a different project (no information leak).
func (s *SQLiteStore) GetProjectAllowlistEntry(
	ctx context.Context,
	projectID, allowlistID string,
) (*AllowlistEntry, error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT allowlist_id, project_id, detector, allowlist_key,
		       reason, created_by, created_at, match_count
		FROM project_detector_allowlist
		WHERE project_id = ? AND allowlist_id = ?
	`, projectID, allowlistID)

	e := &AllowlistEntry{}
	if err := row.Scan(
		&e.AllowlistID, &e.ProjectID, &e.Detector, &e.AllowlistKey,
		&e.Reason, &e.CreatedBy, &e.CreatedAt, &e.MatchCount,
	); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("get project_detector_allowlist: %w", err)
	}
	return e, nil
}

// CreateProjectAllowlistEntry inserts a new allowlist row. Caller
// has already validated the input (detector / key / reason length /
// PROJECT_ALLOWLIST_MAX). e.AllowlistID is server-generated by the
// caller. CreatedAt is overwritten here to ensure monotonic order
// regardless of clock skew at the handler.
func (s *SQLiteStore) CreateProjectAllowlistEntry(
	ctx context.Context,
	e *AllowlistEntry,
) error {
	createdAt := time.Now().UTC().Format(time.RFC3339)
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO project_detector_allowlist
		  (allowlist_id, project_id, detector, allowlist_key,
		   reason, created_by, created_at, match_count)
		VALUES (?, ?, ?, ?, ?, ?, ?, 0)
	`,
		e.AllowlistID, e.ProjectID, e.Detector, e.AllowlistKey,
		e.Reason, e.CreatedBy, createdAt,
	)
	if err != nil {
		return fmt.Errorf("create project_detector_allowlist: %w", err)
	}
	e.CreatedAt = createdAt
	e.MatchCount = 0
	return nil
}

// UpdateProjectAllowlistEntry overwrites the mutable fields
// (allowlist_key, reason) of an existing row. project_id +
// allowlist_id must match. created_at / created_by / match_count
// are NOT touched. Returns ErrNotFound when no row matched.
func (s *SQLiteStore) UpdateProjectAllowlistEntry(
	ctx context.Context,
	e *AllowlistEntry,
) error {
	res, err := s.db.ExecContext(ctx, `
		UPDATE project_detector_allowlist
		   SET allowlist_key = ?, reason = ?
		 WHERE project_id = ? AND allowlist_id = ?
	`, e.AllowlistKey, e.Reason, e.ProjectID, e.AllowlistID)
	if err != nil {
		return fmt.Errorf("update project_detector_allowlist: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("update project_detector_allowlist rows-affected: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// DeleteProjectAllowlistEntry removes a row by PK. Returns
// ErrNotFound when (projectID, allowlistID) doesn't exist.
func (s *SQLiteStore) DeleteProjectAllowlistEntry(
	ctx context.Context,
	projectID, allowlistID string,
) error {
	res, err := s.db.ExecContext(ctx, `
		DELETE FROM project_detector_allowlist
		 WHERE project_id = ? AND allowlist_id = ?
	`, projectID, allowlistID)
	if err != nil {
		return fmt.Errorf("delete project_detector_allowlist: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("delete project_detector_allowlist rows-affected: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// CountProjectAllowlistEntries returns the row count for
// (projectID, detector). Used by the handler to enforce
// PROJECT_ALLOWLIST_MAX before CREATE.
func (s *SQLiteStore) CountProjectAllowlistEntries(
	ctx context.Context,
	projectID, detector string,
) (int, error) {
	var n int
	if err := s.db.QueryRowContext(ctx, `
		SELECT COUNT(*)
		FROM project_detector_allowlist
		WHERE project_id = ? AND detector = ?
	`, projectID, detector).Scan(&n); err != nil {
		return 0, fmt.Errorf("count project_detector_allowlist: %w", err)
	}
	return n, nil
}

// CheckAllowlistMatch returns true iff a row exists with
// (project_id, detector, allowlist_key = signature). Used by
// Allowlist.b detector hot path to skip failure_group creation on
// allowlisted signatures. Single indexed query; <1ms typical.
func (s *SQLiteStore) CheckAllowlistMatch(
	ctx context.Context,
	projectID, detector, signature string,
) (bool, error) {
	var n int
	if err := s.db.QueryRowContext(ctx, `
		SELECT COUNT(*)
		FROM project_detector_allowlist
		WHERE project_id = ?
		  AND detector = ?
		  AND allowlist_key = ?
	`, projectID, detector, signature).Scan(&n); err != nil {
		return false, fmt.Errorf("check allowlist match: %w", err)
	}
	return n > 0, nil
}

// IncrementAllowlistMatchCount adds delta to match_count for the
// matched (project_id, detector, allowlist_key) row(s). Used by
// the Allowlist.b detector hot path to keep per-entry telemetry
// visible in the dashboard editor.
//
// We update by (project_id, detector, allowlist_key) rather than
// by allowlist_id because the detector hot path knows the
// signature but not the row's primary key. The query is the same
// shape as CheckAllowlistMatch — same indexed lookup — so cost is
// minimal.
func (s *SQLiteStore) IncrementAllowlistMatchCount(
	ctx context.Context,
	projectID, detector, allowlistKey string,
	delta int,
) error {
	_, err := s.db.ExecContext(ctx, `
		UPDATE project_detector_allowlist
		   SET match_count = match_count + ?
		 WHERE project_id = ?
		   AND detector = ?
		   AND allowlist_key = ?
	`, delta, projectID, detector, allowlistKey)
	if err != nil {
		return fmt.Errorf("increment allowlist match_count: %w", err)
	}
	return nil
}
