/**
 * AUTO-GENERATED by scripts/codegen.py from spec/error_classes.yaml. DO NOT EDIT BY HAND. Re-run codegen after editing the spec.
 */

/** Canonical ErrorClass constants (wire-format values). */
export const ERROR_CLASS_NAMES = {
  RATE_LIMITED: "rate_limited",
  QUOTA_EXHAUSTED: "quota_exhausted",
  INTERNAL_ERROR: "internal_error",
  SERVICE_UNAVAILABLE: "service_unavailable",
  TIMEOUT: "timeout",
  INVALID_API_KEY: "invalid_api_key",
  CLIENT_ERROR: "client_error",
  UNKNOWN: "unknown",
} as const;

/** Subset of ErrorClass values that count as 'provider-side' for
 * the provider_incident detector. */
export const PROVIDER_SIDE_ERROR_CLASS_VALUES: ReadonlySet<string> = new Set([
  "rate_limited", // RATE_LIMITED
  "quota_exhausted", // QUOTA_EXHAUSTED
  "internal_error", // INTERNAL_ERROR
  "service_unavailable", // SERVICE_UNAVAILABLE
  "timeout", // TIMEOUT
]);
