#!/usr/bin/env python3
"""
Codegen for the canonical provider-error vocabulary (/ ).

Reads ``spec/error_classes.yaml`` and writes three target files:

  - sdk-python/mesedi/_error_classes_generated.py
  - sdk-typescript/src/_errorClassesGenerated.ts
  - backend/internal/detectors/provider_error_classes_generated.go

Each target file contains ONLY the canonical class names + the
provider-side filter set. Hand-written errors.py / errors.ts /
provider_error_classes.go import from the generated files so the
three implementations cannot drift apart.

Usage:

    python scripts/codegen.py [--check]

``--check`` exits non-zero if the generated files are out of date
relative to the spec, without writing anything. Use this in CI to
fail the build when the spec is changed but codegen wasn't run.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

# Parse YAML without taking a hard PyYAML dep — the spec is small
# and we control its format. A minimal parser keeps the codegen
# zero-dependency so it can run on any Python install.
try:
    import yaml  # type: ignore[import-not-found]
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False


ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "error_classes.yaml"
PY_OUT = ROOT / "sdk-python" / "mesedi" / "_error_classes_generated.py"
TS_OUT = ROOT / "sdk-typescript" / "src" / "_errorClassesGenerated.ts"
GO_OUT = ROOT / "backend" / "internal" / "detectors" / "provider_error_classes_generated.go"

GENERATED_BANNER = (
    "AUTO-GENERATED by scripts/codegen.py from spec/error_classes.yaml. "
    "DO NOT EDIT BY HAND. Re-run codegen after editing the spec."
)


def load_spec() -> Dict[str, Any]:
    if not SPEC.is_file():
        raise SystemExit(f"spec file missing: {SPEC}")
    text = SPEC.read_text(encoding="utf-8")
    if _HAS_YAML:
        return yaml.safe_load(text)  # type: ignore[no-any-return]
    return _parse_yaml_minimal(text)


def _parse_yaml_minimal(text: str) -> Dict[str, Any]:
    """Tiny YAML subset parser: handles top-level keys, lists of
    strings, lists of dicts with name/value/description fields.
    Enough for spec/error_classes.yaml; replace with PyYAML on any
    machine that needs it for broader specs."""
    classes: List[Dict[str, str]] = []
    provider_side: List[str] = []
    section: str = ""
    current: Dict[str, str] = {}
    pending_desc: List[str] = []
    in_block_scalar = False

    for raw_line in text.splitlines():
        # strip trailing whitespace but preserve indent
        line = raw_line.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            if in_block_scalar and current and pending_desc:
                pending_desc.append("")
            continue

        # Detect end of a block scalar by drop in indentation.
        if in_block_scalar:
            if line.startswith("    ") or line.startswith("\t"):
                pending_desc.append(line.strip())
                continue
            current["description"] = " ".join(p for p in pending_desc if p).strip()
            pending_desc = []
            in_block_scalar = False

        if not line.startswith(" ") and line.endswith(":"):
            # top-level key
            if current and section == "classes":
                classes.append(current)
                current = {}
            section = line[:-1]
            continue

        stripped = line.lstrip()
        if section == "classes":
            if stripped.startswith("- name:"):
                if current:
                    classes.append(current)
                current = {"name": stripped.split(":", 1)[1].strip()}
            elif stripped.startswith("value:"):
                current["value"] = stripped.split(":", 1)[1].strip()
            elif stripped.startswith("description:"):
                # block scalar starts on next indented line
                in_block_scalar = True
                pending_desc = []
        elif section == "provider_side_classes":
            if stripped.startswith("- "):
                provider_side.append(stripped[2:].strip())

    if in_block_scalar and current and pending_desc:
        current["description"] = " ".join(p for p in pending_desc if p).strip()
    if current and section == "classes":
        classes.append(current)

    return {"classes": classes, "provider_side_classes": provider_side}


# ──────────────────────────────────────────────────────────────────────
# Python emitter
# ──────────────────────────────────────────────────────────────────────


def emit_python(spec: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append('"""')
    lines.append(GENERATED_BANNER)
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("# Canonical ErrorClass constants. Values match the wire format.")
    lines.append("ERROR_CLASS_NAMES = {")
    for c in spec["classes"]:
        lines.append(f'    "{c["name"]}": "{c["value"]}",')
    lines.append("}")
    lines.append("")
    lines.append(
        "# Subset of ErrorClass values that count as 'provider-side' for the"
    )
    lines.append("# provider_incident detector.")
    lines.append("PROVIDER_SIDE_ERROR_CLASS_VALUES = frozenset({")
    for name in spec["provider_side_classes"]:
        # Look up the value for this name
        match = next(c for c in spec["classes"] if c["name"] == name)
        lines.append(f'    "{match["value"]}",  # {name}')
    lines.append("})")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────
# TypeScript emitter
# ──────────────────────────────────────────────────────────────────────


def emit_typescript(spec: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("/**")
    lines.append(f" * {GENERATED_BANNER}")
    lines.append(" */")
    lines.append("")
    lines.append("/** Canonical ErrorClass constants (wire-format values). */")
    lines.append("export const ERROR_CLASS_NAMES = {")
    for c in spec["classes"]:
        lines.append(f'  {c["name"]}: "{c["value"]}",')
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Subset of ErrorClass values that count as 'provider-side' for")
    lines.append(" * the provider_incident detector. */")
    lines.append("export const PROVIDER_SIDE_ERROR_CLASS_VALUES: ReadonlySet<string> = new Set([")
    for name in spec["provider_side_classes"]:
        match = next(c for c in spec["classes"] if c["name"] == name)
        lines.append(f'  "{match["value"]}", // {name}')
    lines.append("]);")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────
# Go emitter
# ──────────────────────────────────────────────────────────────────────


def emit_go(spec: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("// " + GENERATED_BANNER)
    lines.append("")
    lines.append("package detectors")
    lines.append("")
    lines.append("// ErrorClassValues maps canonical class names to their wire-")
    lines.append("// format string values.")
    lines.append("var ErrorClassValues = map[string]string{")
    for c in spec["classes"]:
        lines.append(f'\t"{c["name"]}": "{c["value"]}",')
    lines.append("}")
    lines.append("")
    lines.append("// ProviderSideErrorClassValues is the subset of canonical")
    lines.append("// values the provider_incident detector treats as provider-")
    lines.append("// side. Customer-side classes are explicitly excluded.")
    lines.append("var ProviderSideErrorClassValues = map[string]struct{}{")
    for name in spec["provider_side_classes"]:
        match = next(c for c in spec["classes"] if c["name"] == name)
        lines.append(f'\t"{match["value"]}": {{}}, // {name}')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated files are out of date.",
    )
    args = parser.parse_args()

    spec = load_spec()
    targets = [
        (PY_OUT, emit_python(spec)),
        (TS_OUT, emit_typescript(spec)),
        (GO_OUT, emit_go(spec)),
    ]

    stale: List[Path] = []
    for path, content in targets:
        existing = path.read_text(encoding="utf-8") if path.is_file() else ""
        if existing != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
                print(f"wrote: {path.relative_to(ROOT)}")

    if args.check:
        if stale:
            print(
                "codegen out of date; re-run scripts/codegen.py:",
                file=sys.stderr,
            )
            for p in stale:
                print(f"  - {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("codegen up to date.")
        return 0

    if not stale:
        print("codegen up to date; no files written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
